# Generated by Django 6.0.3 on 2026-03-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('fullname', models.CharField(db_column='fullName')),
                ('company', models.CharField()),
                ('streetline1', models.CharField(db_column='streetLine1')),
                ('streetline2', models.CharField(db_column='streetLine2')),
                ('city', models.CharField()),
                ('province', models.CharField()),
                ('postalcode', models.CharField(db_column='postalCode')),
                ('phonenumber', models.CharField(db_column='phoneNumber')),
                ('defaultshippingaddress', models.BooleanField(db_column='defaultShippingAddress')),
                ('defaultbillingaddress', models.BooleanField(db_column='defaultBillingAddress')),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('deletedat', models.DateTimeField(blank=True, db_column='deletedAt', null=True)),
                ('firstname', models.CharField(db_column='firstName')),
                ('lastname', models.CharField(db_column='lastName')),
                ('emailaddress', models.CharField(db_column='emailAddress', unique=True)),
            ],
            options={
                'db_table': 'administrator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('name', models.CharField()),
                ('type', models.CharField()),
                ('mimetype', models.CharField(db_column='mimeType')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('filesize', models.IntegerField(db_column='fileSize')),
                ('source', models.CharField()),
                ('preview', models.CharField()),
                ('focalpoint', models.TextField(blank=True, db_column='focalPoint', null=True)),
            ],
            options={
                'db_table': 'asset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetChannelsChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'asset_channels_channel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetTagsTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'asset_tags_tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthenticationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('identifier', models.CharField(blank=True, null=True)),
                ('passwordhash', models.CharField(blank=True, db_column='passwordHash', null=True)),
                ('verificationtoken', models.CharField(blank=True, db_column='verificationToken', null=True)),
                ('passwordresettoken', models.CharField(blank=True, db_column='passwordResetToken', null=True)),
                ('identifierchangetoken', models.CharField(blank=True, db_column='identifierChangeToken', null=True)),
                ('pendingidentifier', models.CharField(blank=True, db_column='pendingIdentifier', null=True)),
                ('strategy', models.CharField(blank=True, null=True)),
                ('externalidentifier', models.CharField(blank=True, db_column='externalIdentifier', null=True)),
                ('metadata', models.TextField(blank=True, null=True)),
                ('type', models.CharField()),
            ],
            options={
                'db_table': 'authentication_method',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('code', models.CharField(unique=True)),
                ('token', models.CharField(unique=True)),
                ('description', models.CharField(blank=True, null=True)),
                ('defaultlanguagecode', models.CharField(db_column='defaultLanguageCode')),
                ('availablelanguagecodes', models.TextField(blank=True, db_column='availableLanguageCodes', null=True)),
                ('defaultcurrencycode', models.CharField(db_column='defaultCurrencyCode')),
                ('availablecurrencycodes', models.TextField(blank=True, db_column='availableCurrencyCodes', null=True)),
                ('trackinventory', models.BooleanField(db_column='trackInventory')),
                ('outofstockthreshold', models.IntegerField(db_column='outOfStockThreshold')),
                ('pricesincludetax', models.BooleanField(db_column='pricesIncludeTax')),
            ],
            options={
                'db_table': 'channel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('isroot', models.BooleanField(db_column='isRoot')),
                ('position', models.IntegerField()),
                ('isprivate', models.BooleanField(db_column='isPrivate')),
                ('filters', models.TextField()),
                ('inheritfilters', models.BooleanField(db_column='inheritFilters')),
            ],
            options={
                'db_table': 'collection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CollectionAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('position', models.IntegerField()),
            ],
            options={
                'db_table': 'collection_asset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CollectionChannelsChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'collection_channels_channel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CollectionClosure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'collection_closure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CollectionProductVariantsProductVariant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'collection_product_variants_product_variant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CollectionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('languagecode', models.CharField(db_column='languageCode')),
                ('name', models.CharField()),
                ('slug', models.CharField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'collection_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('deletedat', models.DateTimeField(blank=True, db_column='deletedAt', null=True)),
                ('title', models.CharField(blank=True, null=True)),
                ('firstname', models.CharField(db_column='firstName')),
                ('lastname', models.CharField(db_column='lastName')),
                ('phonenumber', models.CharField(blank=True, db_column='phoneNumber', null=True)),
                ('emailaddress', models.CharField(db_column='emailAddress')),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerChannelsChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'customer_channels_channel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('name', models.CharField()),
            ],
            options={
                'db_table': 'customer_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerGroupsCustomerGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'customer_groups_customer_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('isprivate', models.BooleanField(db_column='isPrivate')),
                ('code', models.CharField(unique=True)),
            ],
            options={
                'db_table': 'facet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacetChannelsChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'facet_channels_channel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacetTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('languagecode', models.CharField(db_column='languageCode')),
                ('name', models.CharField()),
            ],
            options={
                'db_table': 'facet_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacetValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('code', models.CharField()),
            ],
            options={
                'db_table': 'facet_value',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacetValueChannelsChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'facet_value_channels_channel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacetValueTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('languagecode', models.CharField(db_column='languageCode')),
                ('name', models.CharField()),
            ],
            options={
                'db_table': 'facet_value_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('state', models.CharField()),
                ('trackingcode', models.CharField(db_column='trackingCode')),
                ('method', models.CharField()),
                ('handlercode', models.CharField(db_column='handlerCode')),
            ],
            options={
                'db_table': 'fulfillment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('availablelanguages', models.TextField(db_column='availableLanguages')),
                ('trackinventory', models.BooleanField(db_column='trackInventory')),
                ('outofstockthreshold', models.IntegerField(db_column='outOfStockThreshold')),
            ],
            options={
                'db_table': 'global_settings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('type', models.CharField()),
                ('ispublic', models.BooleanField(db_column='isPublic')),
                ('data', models.TextField()),
                ('discriminator', models.CharField()),
            ],
            options={
                'db_table': 'history_entry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('queuename', models.CharField(db_column='queueName')),
                ('data', models.TextField(blank=True, null=True)),
                ('state', models.CharField()),
                ('progress', models.IntegerField()),
                ('result', models.TextField(blank=True, null=True)),
                ('error', models.CharField(blank=True, null=True)),
                ('startedat', models.DateTimeField(blank=True, db_column='startedAt', null=True)),
                ('settledat', models.DateTimeField(blank=True, db_column='settledAt', null=True)),
                ('issettled', models.BooleanField(db_column='isSettled')),
                ('retries', models.IntegerField()),
                ('attempts', models.IntegerField()),
            ],
            options={
                'db_table': 'job_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobRecordBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('bufferid', models.CharField(db_column='bufferId')),
                ('job', models.TextField()),
            ],
            options={
                'db_table': 'job_record_buffer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Migrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField()),
                ('name', models.CharField()),
            ],
            options={
                'db_table': 'migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('type', models.CharField()),
                ('code', models.CharField(unique=True)),
                ('state', models.CharField()),
                ('active', models.BooleanField()),
                ('orderplacedat', models.DateTimeField(blank=True, db_column='orderPlacedAt', null=True)),
                ('couponcodes', models.TextField(db_column='couponCodes')),
                ('shippingaddress', models.TextField(db_column='shippingAddress')),
                ('billingaddress', models.TextField(db_column='billingAddress')),
                ('currencycode', models.CharField(db_column='currencyCode')),
                ('taxzoneid', models.IntegerField(blank=True, db_column='taxZoneId', null=True)),
                ('subtotal', models.IntegerField(db_column='subTotal')),
                ('subtotalwithtax', models.IntegerField(db_column='subTotalWithTax')),
                ('shipping', models.IntegerField()),
                ('shippingwithtax', models.IntegerField(db_column='shippingWithTax')),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderChannelsChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'order_channels_channel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderFulfillmentsFulfillment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'order_fulfillments_fulfillment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('quantity', models.IntegerField()),
                ('orderplacedquantity', models.IntegerField(db_column='orderPlacedQuantity')),
                ('listpriceincludestax', models.BooleanField(db_column='listPriceIncludesTax')),
                ('adjustments', models.TextField()),
                ('taxlines', models.TextField(db_column='taxLines')),
                ('initiallistprice', models.IntegerField(blank=True, db_column='initialListPrice', null=True)),
                ('listprice', models.IntegerField(db_column='listPrice')),
            ],
            options={
                'db_table': 'order_line',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderLineReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('quantity', models.IntegerField()),
                ('discriminator', models.CharField()),
            ],
            options={
                'db_table': 'order_line_reference',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('note', models.CharField()),
                ('shippingaddresschange', models.TextField(blank=True, db_column='shippingAddressChange', null=True)),
                ('billingaddresschange', models.TextField(blank=True, db_column='billingAddressChange', null=True)),
                ('pricechange', models.IntegerField(db_column='priceChange')),
            ],
            options={
                'db_table': 'order_modification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderPromotionsPromotion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'order_promotions_promotion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('method', models.CharField()),
                ('state', models.CharField()),
                ('errormessage', models.CharField(blank=True, db_column='errorMessage', null=True)),
                ('transactionid', models.CharField(blank=True, db_column='transactionId', null=True)),
                ('metadata', models.TextField()),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('code', models.CharField()),
                ('enabled', models.BooleanField()),
                ('checker', models.TextField(blank=True, null=True)),
                ('handler', models.TextField()),
            ],
            options={
                'db_table': 'payment_method',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodChannelsChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'payment_method_channels_channel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('languagecode', models.CharField(db_column='languageCode')),
                ('name', models.CharField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'payment_method_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('deletedat', models.DateTimeField(blank=True, db_column='deletedAt', null=True)),
                ('enabled', models.BooleanField()),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('position', models.IntegerField()),
            ],
            options={
                'db_table': 'product_asset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductChannelsChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'product_channels_channel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductFacetValuesFacetValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'product_facet_values_facet_value',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('deletedat', models.DateTimeField(blank=True, db_column='deletedAt', null=True)),
                ('code', models.CharField()),
            ],
            options={
                'db_table': 'product_option',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductOptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('deletedat', models.DateTimeField(blank=True, db_column='deletedAt', null=True)),
                ('code', models.CharField()),
            ],
            options={
                'db_table': 'product_option_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductOptionGroupTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('languagecode', models.CharField(db_column='languageCode')),
                ('name', models.CharField()),
            ],
            options={
                'db_table': 'product_option_group_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductOptionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('languagecode', models.CharField(db_column='languageCode')),
                ('name', models.CharField()),
            ],
            options={
                'db_table': 'product_option_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('languagecode', models.CharField(db_column='languageCode')),
                ('name', models.CharField()),
                ('slug', models.CharField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'product_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('deletedat', models.DateTimeField(blank=True, db_column='deletedAt', null=True)),
                ('enabled', models.BooleanField()),
                ('sku', models.CharField()),
                ('outofstockthreshold', models.IntegerField(db_column='outOfStockThreshold')),
                ('useglobaloutofstockthreshold', models.BooleanField(db_column='useGlobalOutOfStockThreshold')),
                ('trackinventory', models.CharField(db_column='trackInventory')),
            ],
            options={
                'db_table': 'product_variant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariantAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('position', models.IntegerField()),
            ],
            options={
                'db_table': 'product_variant_asset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariantChannelsChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'product_variant_channels_channel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariantFacetValuesFacetValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'product_variant_facet_values_facet_value',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariantOptionsProductOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'product_variant_options_product_option',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariantPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('currencycode', models.CharField(db_column='currencyCode')),
                ('channelid', models.IntegerField(blank=True, db_column='channelId', null=True)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'product_variant_price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariantTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('languagecode', models.CharField(db_column='languageCode')),
                ('name', models.CharField()),
            ],
            options={
                'db_table': 'product_variant_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('deletedat', models.DateTimeField(blank=True, db_column='deletedAt', null=True)),
                ('startsat', models.DateTimeField(blank=True, db_column='startsAt', null=True)),
                ('endsat', models.DateTimeField(blank=True, db_column='endsAt', null=True)),
                ('couponcode', models.CharField(blank=True, db_column='couponCode', null=True)),
                ('percustomerusagelimit', models.IntegerField(blank=True, db_column='perCustomerUsageLimit', null=True)),
                ('usagelimit', models.IntegerField(blank=True, db_column='usageLimit', null=True)),
                ('enabled', models.BooleanField()),
                ('conditions', models.TextField()),
                ('actions', models.TextField()),
                ('priorityscore', models.IntegerField(db_column='priorityScore')),
            ],
            options={
                'db_table': 'promotion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PromotionChannelsChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'promotion_channels_channel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PromotionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('languagecode', models.CharField(db_column='languageCode')),
                ('name', models.CharField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'promotion_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('method', models.CharField()),
                ('reason', models.CharField(blank=True, null=True)),
                ('state', models.CharField()),
                ('transactionid', models.CharField(blank=True, db_column='transactionId', null=True)),
                ('metadata', models.TextField()),
                ('items', models.IntegerField()),
                ('shipping', models.IntegerField()),
                ('adjustment', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'refund',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('code', models.CharField()),
                ('type', models.CharField()),
                ('enabled', models.BooleanField()),
                ('discriminator', models.CharField()),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('languagecode', models.CharField(db_column='languageCode')),
                ('name', models.CharField()),
            ],
            options={
                'db_table': 'region_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('code', models.CharField()),
                ('description', models.CharField()),
                ('permissions', models.TextField()),
            ],
            options={
                'db_table': 'role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoleChannelsChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'role_channels_channel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduledTaskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('taskid', models.CharField(db_column='taskId', unique=True)),
                ('enabled', models.BooleanField()),
                ('lockedat', models.DateTimeField(blank=True, db_column='lockedAt', null=True)),
                ('lastexecutedat', models.DateTimeField(blank=True, db_column='lastExecutedAt', null=True)),
                ('manuallytriggeredat', models.DateTimeField(blank=True, db_column='manuallyTriggeredAt', null=True)),
                ('lastresult', models.TextField(blank=True, db_column='lastResult', null=True)),
            ],
            options={
                'db_table': 'scheduled_task_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SearchIndexItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('languagecode', models.CharField(db_column='languageCode')),
                ('enabled', models.BooleanField()),
                ('productname', models.CharField(db_column='productName')),
                ('productvariantname', models.CharField(db_column='productVariantName')),
                ('description', models.TextField()),
                ('slug', models.CharField()),
                ('sku', models.CharField()),
                ('facetids', models.TextField(db_column='facetIds')),
                ('facetvalueids', models.TextField(db_column='facetValueIds')),
                ('collectionids', models.TextField(db_column='collectionIds')),
                ('collectionslugs', models.TextField(db_column='collectionSlugs')),
                ('channelids', models.TextField(db_column='channelIds')),
                ('productpreview', models.CharField(db_column='productPreview')),
                ('productpreviewfocalpoint', models.TextField(blank=True, db_column='productPreviewFocalPoint', null=True)),
                ('productvariantpreview', models.CharField(db_column='productVariantPreview')),
                ('productvariantpreviewfocalpoint', models.TextField(blank=True, db_column='productVariantPreviewFocalPoint', null=True)),
                ('instock', models.BooleanField(db_column='inStock')),
                ('productinstock', models.BooleanField(db_column='productInStock')),
                ('productvariantid', models.IntegerField(db_column='productVariantId')),
                ('channelid', models.IntegerField(db_column='channelId')),
                ('productid', models.IntegerField(db_column='productId')),
                ('productassetid', models.IntegerField(blank=True, db_column='productAssetId', null=True)),
                ('productvariantassetid', models.IntegerField(blank=True, db_column='productVariantAssetId', null=True)),
                ('price', models.IntegerField()),
                ('pricewithtax', models.IntegerField(db_column='priceWithTax')),
            ],
            options={
                'db_table': 'search_index_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('deletedat', models.DateTimeField(blank=True, db_column='deletedAt', null=True)),
                ('name', models.CharField()),
            ],
            options={
                'db_table': 'seller',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('token', models.CharField(unique=True)),
                ('expires', models.DateTimeField()),
                ('invalidated', models.BooleanField()),
                ('authenticationstrategy', models.CharField(blank=True, db_column='authenticationStrategy', null=True)),
                ('type', models.CharField()),
            ],
            options={
                'db_table': 'session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SettingsStoreEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('key', models.CharField()),
                ('value', models.TextField(blank=True, null=True)),
                ('scope', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'settings_store_entry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('listpriceincludestax', models.BooleanField(db_column='listPriceIncludesTax')),
                ('adjustments', models.TextField()),
                ('taxlines', models.TextField(db_column='taxLines')),
                ('listprice', models.IntegerField(db_column='listPrice')),
            ],
            options={
                'db_table': 'shipping_line',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('deletedat', models.DateTimeField(blank=True, db_column='deletedAt', null=True)),
                ('code', models.CharField()),
                ('checker', models.TextField()),
                ('calculator', models.TextField()),
                ('fulfillmenthandlercode', models.CharField(db_column='fulfillmentHandlerCode')),
            ],
            options={
                'db_table': 'shipping_method',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingMethodChannelsChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'shipping_method_channels_channel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingMethodTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('languagecode', models.CharField(db_column='languageCode')),
                ('name', models.CharField()),
                ('description', models.CharField()),
            ],
            options={
                'db_table': 'shipping_method_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('stockonhand', models.IntegerField(db_column='stockOnHand')),
                ('stockallocated', models.IntegerField(db_column='stockAllocated')),
            ],
            options={
                'db_table': 'stock_level',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('name', models.CharField()),
                ('description', models.CharField()),
            ],
            options={
                'db_table': 'stock_location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockLocationChannelsChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'stock_location_channels_channel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('type', models.CharField()),
                ('quantity', models.IntegerField()),
                ('discriminator', models.CharField()),
            ],
            options={
                'db_table': 'stock_movement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Surcharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('description', models.CharField()),
                ('listpriceincludestax', models.BooleanField(db_column='listPriceIncludesTax')),
                ('sku', models.CharField()),
                ('taxlines', models.TextField(db_column='taxLines')),
                ('listprice', models.IntegerField(db_column='listPrice')),
            ],
            options={
                'db_table': 'surcharge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('value', models.CharField()),
            ],
            options={
                'db_table': 'tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaxCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('name', models.CharField()),
                ('isdefault', models.BooleanField(db_column='isDefault')),
            ],
            options={
                'db_table': 'tax_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('name', models.CharField()),
                ('enabled', models.BooleanField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'tax_rate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('deletedat', models.DateTimeField(blank=True, db_column='deletedAt', null=True)),
                ('identifier', models.CharField()),
                ('verified', models.BooleanField()),
                ('lastlogin', models.DateTimeField(blank=True, db_column='lastLogin', null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRolesRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_roles_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
                ('name', models.CharField()),
            ],
            options={
                'db_table': 'zone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZoneMembersRegion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'zone_members_region',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
