"""
Django settings for setup project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv  import load_dotenv 
import dj_database_url
import os


load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False')

ALLOWED_HOSTS = [os.getenv('DJANGO_ALLOWED_HOSTS'), 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    "unfold",  # Must be before django.contrib.admin
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.inlines",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "app.apps.AppConfig",
]

# Unfold settings for a "Shopify Apps" aesthetic
from django.templatetags.static import static
UNFOLD = {
    "SITE_TITLE": "mukhtaleefweart Admin",
    "SITE_HEADER": "mukhtaleefweart",
    "COLORS": {
        "primary": {
            "50": "240 253 244",
            "100": "220 252 231",
            "200": "187 247 208",
            "300": "134 239 172",
            "400": "74 222 128",
            "500": "34 197 94",  # Shopify typically uses a distinctive green shade
            "600": "22 163 74",
            "700": "21 128 61",
            "800": "22 101 52",
            "900": "20 83 45",
            "950": "5 46 22",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Shop",
                "separator": True,
                "items": [
                    {"title": "Orders",    "icon": "shopping_cart",   "link": "/admin/app/order/"},
                    {"title": "Customers", "icon": "group",           "link": "/admin/app/customer/"},
                    {"title": "Payments",  "icon": "payments",        "link": "/admin/app/payment/"},
                    {"title": "Refunds",   "icon": "undo",            "link": "/admin/app/refund/"},
                ],
            },
            {
                "title": "Catalog",
                "separator": True,
                "items": [
                    {"title": "Products",          "icon": "inventory_2",   "link": "/admin/app/product/"},
                    {"title": "Product Variants",  "icon": "layers",        "link": "/admin/app/productvariant/"},
                    {"title": "Collections",       "icon": "category",      "link": "/admin/app/collection/"},
                    {"title": "Facets",            "icon": "filter_list",   "link": "/admin/app/facet/"},
                    {"title": "Facet Values",      "icon": "label",         "link": "/admin/app/facetvalue/"},
                    {"title": "Tags",              "icon": "sell",          "link": "/admin/app/tag/"},
                    {"title": "Assets / Media",    "icon": "photo_library", "link": "/admin/app/asset/"},
                ],
            },
            {
                "title": "Inventory",
                "separator": True,
                "items": [
                    {"title": "Stock Levels",    "icon": "inventory",       "link": "/admin/app/stocklevel/"},
                    {"title": "Stock Locations", "icon": "warehouse",       "link": "/admin/app/stocklocation/"},
                    {"title": "Fulfillments",    "icon": "local_shipping",  "link": "/admin/app/fulfillment/"},
                ],
            },
            {
                "title": "Marketing",
                "separator": True,
                "items": [
                    {"title": "Promotions", "icon": "campaign", "link": "/admin/app/promotion/"},
                    {"title": "Channels",   "icon": "hub",      "link": "/admin/app/channel/"},
                ],
            },
            {
                "title": "Settings",
                "separator": True,
                "items": [
                    {"title": "Global Settings",  "icon": "settings",             "link": "/admin/app/globalsettings/"},
                    {"title": "Shipping Methods", "icon": "local_shipping",        "link": "/admin/app/shippingmethod/"},
                    {"title": "Tax Categories",   "icon": "percent",               "link": "/admin/app/taxcategory/"},
                    {"title": "Zones",            "icon": "map",                   "link": "/admin/app/zone/"},
                    {"title": "Admins & Staff",   "icon": "admin_panel_settings",  "link": "/admin/app/user/"},
                ],
            },
        ],
    },
    "DASHBOARD_CALLBACK": "app.admin_dashboard.dashboard_callback",
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'setup.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'app.context_processors.cart_processor',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'setup.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


try:
    if os.getenv('DATABASE_HOST'):
        DATABASES = {
            # 'default': {
            #     'ENGINE': 'django.db.backends.postgresql',
            #     'NAME': os.getenv('DATABASE_NAME'),
            #     'USER': os.getenv('DATABASE_USER'),
            #     'PASSWORD': os.getenv('DATABASE_PASSWORD'),
            #     'HOST': os.getenv('DATABASE_HOST'),
            #     'PORT': os.getenv('DATABASE_PORT'),
            # }
            'default': dj_database_url.config(
                default=os.getenv('DATABASE_HOST'),
                conn_max_age=600,
                conn_health_checks=True,
            )
        }
except Exception:
    if not os.getenv('DATABASE_HOST'):
        DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Karachi'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Email Settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@storedjreheel.com')


